package de.hwrberlin.it2014.sweproject.cbr;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import de.hwrberlin.it2014.sweproject.database.DatabaseConnection;
import de.hwrberlin.it2014.sweproject.database.TableResultsSQL;
import de.hwrberlin.it2014.sweproject.model.Judgement;
import de.hwrberlin.it2014.sweproject.model.Result;

/**
 * 
 * @author Max Bock & Felix Lehmann
 *
 */
public class Request {
	
	private ArrayList<String> description;
	private ScoreProcessor<Judgement> scoreProc;
	private Date dateOfRequest;
	
	/**
	 * @author Max Bock
	 * @param userInput
	 */
	public Request(ArrayList<String> userInput)
	{
		description = userInput;
		scoreProc = new ScoreProcessor<Judgement>();
		dateOfRequest = new Date();
	}
	
	public Date getDateOfRequest() 
	{
		return dateOfRequest;
	}
	
	/**
	 * @author Max Bock
	 * @return UserInput as String - Stringwords separated by Space
	 */
	public String getDescription()
	{
		String sstream = "";
		for (String s : description)
		{
			sstream += s + " ";
		}
		return sstream;
	}
	
	/**
	 * gibt die Beschreibung (User Input) als ArrayList zurück
	 * @author Max Bock
	 * @param asList boolean (wert egal)
	 * @return UserInput as ArrayList<String>
	 */
	public ArrayList<String> getDescription(boolean asList)
	{
		return description;
	}
	
	/**
	 * Fragt die DB nach ähnlichen Fällen, konvertiert sie in Results und speichert diese erneut in der DB,
	 * 	sodass später die Nutzerwertung eingetragen werden kann
	 * @author Max Bock
	 * @param count of sets to return 
	 * @return ArrayList<Result> containing all similiar cases from DB
	 * @throws SQLException
	 */
	public ArrayList<Result> getSimilarFromDB(int number) throws SQLException
	{
		ArrayList<Judgement> similarCases = scoreProc.getBestMatches(description, number, (long) -1, null); 
		//TODO separate the timestamp and lawsector from userinput
	    return writeJudgementToDBAsResult(similarCases);
	}
	
	/**
	 * erzeugt ein Resultobjekt aus einem Judgement für diesen Fall(also mit der aktuellen Useranfrage)
	 * @author Max Bock
	 * @param Judgement
	 * @return Result
	 */
	private Result newResultFromJudgement(Judgement j) 
	{
		Result r=new Result(
				this.getDescription(), //String: userInput
				j, //Judgement: a single similarCase
				(float) scoreProc.getCachedScore(j), //float: similarity
				this.dateOfRequest); //Date: Date of request
		return r;
	}

	/**
	 * erzeugt aus der Liste ähnliche Fälle (Judgement) zu dieser Anfrage eine ArrayList<Result>,
	 * speichert diese in der Datenbank und schreibt die von der DB vergebenen ID in das jeweilige Result
	 * und gibt die Liste am Ende zurück
	 * @author Max Bock
	 * @param judgList - ArrayList<Judgement>
	 * @return ArrayList<Result>
	 */
	private ArrayList<Result> writeJudgementToDBAsResult(ArrayList<Judgement> judgList)
	{
		DatabaseConnection dbc=new DatabaseConnection();
		dbc.connectToMysql();
		ArrayList<Result> resList = new ArrayList<>();
		for(Judgement j : judgList) //loop for every similarCase
		{
			Result r = newResultFromJudgement(j);
			int id=0; //will be set later
			String sql = TableResultsSQL.getInsertSQLCode(r);
			try { //write to DB; userRating will be updated in CBR.saveUserRating
				id = dbc.executeUpdateRetrieveID(sql); 
			} catch (SQLException e) {
				e.printStackTrace();
			}
			//set autoGenerated ID to current Result
			r.setID(id);
			resList.add(r); //add current Result to List
		}
		return resList;
	}
}